# Generated by Django 5.1.6 on 2025-02-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("en_cours", "En cours"),
                    ("résolu", "Résolu"),
                ],
                default="nouveau",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
