# Generated by Django 5.1.6 on 2025-02-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_incident_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="new",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
