# Generated by Django 5.1.6 on 2025-03-03 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0007_incidentfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IncidentAttachment",
        ),
    ]
