# Generated by Django 5.1.6 on 2025-03-22 18:28

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0008_delete_incidentattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="details",
            field=django_quill.fields.QuillField(),
        ),
    ]
