# Generated by Django 5.1.6 on 2025-03-22 21:09

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0009_alter_incident_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="impact",
            field=django_quill.fields.QuillField(),
        ),
    ]
